/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerRefreshTokenRequest
 */
export interface AdminAuthControllerRefreshTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerRefreshTokenRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerRefreshTokenRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AdminAuthControllerRefreshTokenRequest interface.
 */
export function instanceOfAdminAuthControllerRefreshTokenRequest(value: object): value is AdminAuthControllerRefreshTokenRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AdminAuthControllerRefreshTokenRequestFromJSON(json: any): AdminAuthControllerRefreshTokenRequest {
    return AdminAuthControllerRefreshTokenRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerRefreshTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerRefreshTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'refreshToken': json['refreshToken'],
    };
}

export function AdminAuthControllerRefreshTokenRequestToJSON(json: any): AdminAuthControllerRefreshTokenRequest {
    return AdminAuthControllerRefreshTokenRequestToJSONTyped(json, false);
}

export function AdminAuthControllerRefreshTokenRequestToJSONTyped(value?: AdminAuthControllerRefreshTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'refreshToken': value['refreshToken'],
    };
}

