/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerEnableMfaRequest
 */
export interface AdminAuthControllerEnableMfaRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerEnableMfaRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerEnableMfaRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerEnableMfaRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerEnableMfaRequest
     */
    deviceName: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerEnableMfaRequest
     */
    answerChallenge: AdminAuthControllerEnableMfaRequestAnswerChallengeEnum;
}


/**
 * @export
 */
export const AdminAuthControllerEnableMfaRequestAnswerChallengeEnum = {
    CUSTOM_CHALLENGE: 'CUSTOM_CHALLENGE',
    MFA_SETUP: 'MFA_SETUP',
    NEW_PASSWORD_REQUIRED: 'NEW_PASSWORD_REQUIRED',
    SELECT_MFA_TYPE: 'SELECT_MFA_TYPE',
    SMS_MFA: 'SMS_MFA',
    SOFTWARE_TOKEN_MFA: 'SOFTWARE_TOKEN_MFA'
} as const;
export type AdminAuthControllerEnableMfaRequestAnswerChallengeEnum = typeof AdminAuthControllerEnableMfaRequestAnswerChallengeEnum[keyof typeof AdminAuthControllerEnableMfaRequestAnswerChallengeEnum];


/**
 * Check if a given object implements the AdminAuthControllerEnableMfaRequest interface.
 */
export function instanceOfAdminAuthControllerEnableMfaRequest(value: object): value is AdminAuthControllerEnableMfaRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('deviceName' in value) || value['deviceName'] === undefined) return false;
    if (!('answerChallenge' in value) || value['answerChallenge'] === undefined) return false;
    return true;
}

export function AdminAuthControllerEnableMfaRequestFromJSON(json: any): AdminAuthControllerEnableMfaRequest {
    return AdminAuthControllerEnableMfaRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerEnableMfaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerEnableMfaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'code': json['code'],
        'deviceName': json['deviceName'],
        'answerChallenge': json['answerChallenge'],
    };
}

export function AdminAuthControllerEnableMfaRequestToJSON(json: any): AdminAuthControllerEnableMfaRequest {
    return AdminAuthControllerEnableMfaRequestToJSONTyped(json, false);
}

export function AdminAuthControllerEnableMfaRequestToJSONTyped(value?: AdminAuthControllerEnableMfaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'code': value['code'],
        'deviceName': value['deviceName'],
        'answerChallenge': value['answerChallenge'],
    };
}

