/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerForgotPasswordRequest
 */
export interface AdminAuthControllerForgotPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerForgotPasswordRequest
     */
    email: string;
}

/**
 * Check if a given object implements the AdminAuthControllerForgotPasswordRequest interface.
 */
export function instanceOfAdminAuthControllerForgotPasswordRequest(value: object): value is AdminAuthControllerForgotPasswordRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AdminAuthControllerForgotPasswordRequestFromJSON(json: any): AdminAuthControllerForgotPasswordRequest {
    return AdminAuthControllerForgotPasswordRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerForgotPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerForgotPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AdminAuthControllerForgotPasswordRequestToJSON(json: any): AdminAuthControllerForgotPasswordRequest {
    return AdminAuthControllerForgotPasswordRequestToJSONTyped(json, false);
}

export function AdminAuthControllerForgotPasswordRequestToJSONTyped(value?: AdminAuthControllerForgotPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

