/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerSetUpMfaRequest
 */
export interface AdminAuthControllerSetUpMfaRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSetUpMfaRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSetUpMfaRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AdminAuthControllerSetUpMfaRequest interface.
 */
export function instanceOfAdminAuthControllerSetUpMfaRequest(value: object): value is AdminAuthControllerSetUpMfaRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AdminAuthControllerSetUpMfaRequestFromJSON(json: any): AdminAuthControllerSetUpMfaRequest {
    return AdminAuthControllerSetUpMfaRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerSetUpMfaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerSetUpMfaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AdminAuthControllerSetUpMfaRequestToJSON(json: any): AdminAuthControllerSetUpMfaRequest {
    return AdminAuthControllerSetUpMfaRequestToJSONTyped(json, false);
}

export function AdminAuthControllerSetUpMfaRequestToJSONTyped(value?: AdminAuthControllerSetUpMfaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

