/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerSigninRequest
 */
export interface AdminAuthControllerSigninRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSigninRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSigninRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSigninRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the AdminAuthControllerSigninRequest interface.
 */
export function instanceOfAdminAuthControllerSigninRequest(value: object): value is AdminAuthControllerSigninRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AdminAuthControllerSigninRequestFromJSON(json: any): AdminAuthControllerSigninRequest {
    return AdminAuthControllerSigninRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerSigninRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerSigninRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function AdminAuthControllerSigninRequestToJSON(json: any): AdminAuthControllerSigninRequest {
    return AdminAuthControllerSigninRequestToJSONTyped(json, false);
}

export function AdminAuthControllerSigninRequestToJSONTyped(value?: AdminAuthControllerSigninRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'code': value['code'],
    };
}

