/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerDisableMfaRequest
 */
export interface AdminAuthControllerDisableMfaRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerDisableMfaRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerDisableMfaRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerDisableMfaRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AdminAuthControllerDisableMfaRequest interface.
 */
export function instanceOfAdminAuthControllerDisableMfaRequest(value: object): value is AdminAuthControllerDisableMfaRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AdminAuthControllerDisableMfaRequestFromJSON(json: any): AdminAuthControllerDisableMfaRequest {
    return AdminAuthControllerDisableMfaRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerDisableMfaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerDisableMfaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'code': json['code'],
    };
}

export function AdminAuthControllerDisableMfaRequestToJSON(json: any): AdminAuthControllerDisableMfaRequest {
    return AdminAuthControllerDisableMfaRequestToJSONTyped(json, false);
}

export function AdminAuthControllerDisableMfaRequestToJSONTyped(value?: AdminAuthControllerDisableMfaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'code': value['code'],
    };
}

