/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerSigninConfirmRequest
 */
export interface AdminAuthControllerSigninConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSigninConfirmRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerSigninConfirmRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AdminAuthControllerSigninConfirmRequest interface.
 */
export function instanceOfAdminAuthControllerSigninConfirmRequest(value: object): value is AdminAuthControllerSigninConfirmRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AdminAuthControllerSigninConfirmRequestFromJSON(json: any): AdminAuthControllerSigninConfirmRequest {
    return AdminAuthControllerSigninConfirmRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerSigninConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerSigninConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function AdminAuthControllerSigninConfirmRequestToJSON(json: any): AdminAuthControllerSigninConfirmRequest {
    return AdminAuthControllerSigninConfirmRequestToJSONTyped(json, false);
}

export function AdminAuthControllerSigninConfirmRequestToJSONTyped(value?: AdminAuthControllerSigninConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

