/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuthControllerChangePasswordRequest
 */
export interface AdminAuthControllerChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerChangePasswordRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerChangePasswordRequest
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerChangePasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuthControllerChangePasswordRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the AdminAuthControllerChangePasswordRequest interface.
 */
export function instanceOfAdminAuthControllerChangePasswordRequest(value: object): value is AdminAuthControllerChangePasswordRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function AdminAuthControllerChangePasswordRequestFromJSON(json: any): AdminAuthControllerChangePasswordRequest {
    return AdminAuthControllerChangePasswordRequestFromJSONTyped(json, false);
}

export function AdminAuthControllerChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthControllerChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function AdminAuthControllerChangePasswordRequestToJSON(json: any): AdminAuthControllerChangePasswordRequest {
    return AdminAuthControllerChangePasswordRequestToJSONTyped(json, false);
}

export function AdminAuthControllerChangePasswordRequestToJSONTyped(value?: AdminAuthControllerChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
        'code': value['code'],
    };
}

