/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerSigninRequest
 */
export interface AuthControllerSigninRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerSigninRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerSigninRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerSigninRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the AuthControllerSigninRequest interface.
 */
export function instanceOfAuthControllerSigninRequest(value: object): value is AuthControllerSigninRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthControllerSigninRequestFromJSON(json: any): AuthControllerSigninRequest {
    return AuthControllerSigninRequestFromJSONTyped(json, false);
}

export function AuthControllerSigninRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerSigninRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function AuthControllerSigninRequestToJSON(json: any): AuthControllerSigninRequest {
    return AuthControllerSigninRequestToJSONTyped(json, false);
}

export function AuthControllerSigninRequestToJSONTyped(value?: AuthControllerSigninRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'code': value['code'],
    };
}

