/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthControllerMe200ResponseMetadata
 */
export interface PublicAuthControllerMe200ResponseMetadata {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseMetadata
     */
    lastSignInTime: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseMetadata
     */
    creationTime: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseMetadata
     */
    lastRefreshTime: string;
}

/**
 * Check if a given object implements the PublicAuthControllerMe200ResponseMetadata interface.
 */
export function instanceOfPublicAuthControllerMe200ResponseMetadata(value: object): value is PublicAuthControllerMe200ResponseMetadata {
    if (!('lastSignInTime' in value) || value['lastSignInTime'] === undefined) return false;
    if (!('creationTime' in value) || value['creationTime'] === undefined) return false;
    if (!('lastRefreshTime' in value) || value['lastRefreshTime'] === undefined) return false;
    return true;
}

export function PublicAuthControllerMe200ResponseMetadataFromJSON(json: any): PublicAuthControllerMe200ResponseMetadata {
    return PublicAuthControllerMe200ResponseMetadataFromJSONTyped(json, false);
}

export function PublicAuthControllerMe200ResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthControllerMe200ResponseMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'lastSignInTime': json['lastSignInTime'],
        'creationTime': json['creationTime'],
        'lastRefreshTime': json['lastRefreshTime'],
    };
}

export function PublicAuthControllerMe200ResponseMetadataToJSON(json: any): PublicAuthControllerMe200ResponseMetadata {
    return PublicAuthControllerMe200ResponseMetadataToJSONTyped(json, false);
}

export function PublicAuthControllerMe200ResponseMetadataToJSONTyped(value?: PublicAuthControllerMe200ResponseMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastSignInTime': value['lastSignInTime'],
        'creationTime': value['creationTime'],
        'lastRefreshTime': value['lastRefreshTime'],
    };
}

