/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthControllerMe200ResponseProviderDataInner
 */
export interface PublicAuthControllerMe200ResponseProviderDataInner {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseProviderDataInner
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseProviderDataInner
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseProviderDataInner
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseProviderDataInner
     */
    photoURL: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerMe200ResponseProviderDataInner
     */
    providerId: string;
}

/**
 * Check if a given object implements the PublicAuthControllerMe200ResponseProviderDataInner interface.
 */
export function instanceOfPublicAuthControllerMe200ResponseProviderDataInner(value: object): value is PublicAuthControllerMe200ResponseProviderDataInner {
    if (!('uid' in value) || value['uid'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('photoURL' in value) || value['photoURL'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function PublicAuthControllerMe200ResponseProviderDataInnerFromJSON(json: any): PublicAuthControllerMe200ResponseProviderDataInner {
    return PublicAuthControllerMe200ResponseProviderDataInnerFromJSONTyped(json, false);
}

export function PublicAuthControllerMe200ResponseProviderDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthControllerMe200ResponseProviderDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'],
        'displayName': json['displayName'],
        'email': json['email'],
        'photoURL': json['photoURL'],
        'providerId': json['providerId'],
    };
}

export function PublicAuthControllerMe200ResponseProviderDataInnerToJSON(json: any): PublicAuthControllerMe200ResponseProviderDataInner {
    return PublicAuthControllerMe200ResponseProviderDataInnerToJSONTyped(json, false);
}

export function PublicAuthControllerMe200ResponseProviderDataInnerToJSONTyped(value?: PublicAuthControllerMe200ResponseProviderDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'displayName': value['displayName'],
        'email': value['email'],
        'photoURL': value['photoURL'],
        'providerId': value['providerId'],
    };
}

