/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthControllerSigninRequest
 */
export interface PublicAuthControllerSigninRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerSigninRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerSigninRequest
     */
    password: string;
}

/**
 * Check if a given object implements the PublicAuthControllerSigninRequest interface.
 */
export function instanceOfPublicAuthControllerSigninRequest(value: object): value is PublicAuthControllerSigninRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PublicAuthControllerSigninRequestFromJSON(json: any): PublicAuthControllerSigninRequest {
    return PublicAuthControllerSigninRequestFromJSONTyped(json, false);
}

export function PublicAuthControllerSigninRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthControllerSigninRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function PublicAuthControllerSigninRequestToJSON(json: any): PublicAuthControllerSigninRequest {
    return PublicAuthControllerSigninRequestToJSONTyped(json, false);
}

export function PublicAuthControllerSigninRequestToJSONTyped(value?: PublicAuthControllerSigninRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

