/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicAuthControllerSignupRequest
 */
export interface PublicAuthControllerSignupRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerSignupRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerSignupRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PublicAuthControllerSignupRequest
     */
    displayName: string;
}

/**
 * Check if a given object implements the PublicAuthControllerSignupRequest interface.
 */
export function instanceOfPublicAuthControllerSignupRequest(value: object): value is PublicAuthControllerSignupRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function PublicAuthControllerSignupRequestFromJSON(json: any): PublicAuthControllerSignupRequest {
    return PublicAuthControllerSignupRequestFromJSONTyped(json, false);
}

export function PublicAuthControllerSignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthControllerSignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'displayName': json['displayName'],
    };
}

export function PublicAuthControllerSignupRequestToJSON(json: any): PublicAuthControllerSignupRequest {
    return PublicAuthControllerSignupRequestToJSONTyped(json, false);
}

export function PublicAuthControllerSignupRequestToJSONTyped(value?: PublicAuthControllerSignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'displayName': value['displayName'],
    };
}

